### ISSUE TITLE
Geräte verknüpfen

### ISSUE THREAD

**Issue by nicoh88** [mach1009/homebridge-http-garagedoor#1]
Hi Matthias,

ich habe mich an die Anleitung im [Wiki](https://github.com/mach1009/homebridge-http-garagedoor/wiki/How-to-setup-a-garage-door-opener-in-Homekit-with-Homematic-CCU2-or-RaspberryMatic) gehalten - läuft soweit.

In meinem Fall muss ich jetzt noch den [Tür-/Fensterkontakt HmIP-SWDO](https://www.elv.de/homematic-funk-schaltaktor-mit-klemmanschluss-zwischenstecker-bausatz.html) (Status) und den potentialfreien Kontakt des [HM-LC-Sw1-Pl-CT](https://www.elv.de/homematic-funk-schaltaktor-mit-klemmanschluss-zwischenstecker-bausatz.html) (Schalter) mit dem CCU Programm verbinden. 

Allerdings bin ich, wie bereits im [Issue](https://github.com/thkl/homebridge-homematic/issues/206) beim [homebridge-homematic Plugin](https://github.com/thkl/homebridge-homematic) geschrieben, (noch) kein HomeMatic-Experte.

**Wie verknüpfe ich nun die die realen Geräte mit dem CCU Programm?** Quasi 7. im Detail erklärt, ähnlich wie bei 1., 2. und 3.

Danke Nico

**Comment by thoduh** [comment]
Punkt 4. (http://[CCU_IP]/config/xmlapi/sysvarlist.cgi) bringt bei mir ein 404 - Not Found.
Hab die Variablen aber bei ioBroker gefunden und diese IDs benutzt.
Jetzt bekomme ich bei HomeKit mein Garagentor angezeigt, allerdings steht es auf "Geöffnet" obwohl geschlossen und beim klick darauf steht da zwar "Schließen...", es passiert aber nichts...

Ich habe die Variablen dann so verknüpft:
![bildschirmfoto 2018-03-03 um 14 46 58](https://user-images.githubusercontent.com/22728076/36934984-d7efcc94-1ef1-11e8-8672-3f8dcd474c5c.png)
Ist das richtig?

Und im Homebridge-Logging steht ständig:
![bildschirmfoto 2018-03-03 um 14 55 19](https://user-images.githubusercontent.com/22728076/36935089-f8a37048-1ef2-11e8-91bd-d892022a76a2.png)

**Comment by mach1009** [comment]
@thoduh sicher, dass du die XML Api installiert hast und der Pfad stimmt? Es muss eine Antwort geben, wenn du die URL aufrufst.

**Comment by mach1009** [comment]
@nicoh88 wo hast du denn den Kontaktsensor angebaut? Oben oder unten? Löst er also aus, wenn das Tor bereits einen spalt geöffnet ist oder erst, wenn es am oberen Anschlag angekommen ist?
Braucht die Torsteuerung einen Impuls?

**Comment by thoduh** [comment]
@mach1009 
Tatsächlich, hatte die XML Api vergessen, Sorry ;-)
Eine Antwort kommt aber nicht, nur eine leere Seite.

Trotzdem funktioniert es jetzt schon besser mit den Variablen, muss aber noch rumspielen, so ganz scheint es noch nicht zu funktionieren...

**Comment by nicoh88** [comment]
@mach1009 Sobald das Tor öffnet, zeigt der Kontaktsensor "geöffnet". Erst von das Tor geschlossen ist, zeigt der Kontaktsensor "geschlossen". Ja genau, das Tor braucht nur einen ein sekündlichen Impuls.
![bildschirmfoto 2018-03-03 um 17 38 13](https://user-images.githubusercontent.com/264264/36936787-ed0af230-1f09-11e8-8dec-3d37cbed18c6.png)
![bildschirmfoto 2018-03-03 um 17 39 31](https://user-images.githubusercontent.com/264264/36936788-ed275ff6-1f09-11e8-9e15-5a7f40f671e6.png)

**Comment by mach1009** [comment]
@nicoh88

Denke dein Programm sollte so aussehen:

Wenn
Target = Open
Und
DeinSensor = Closed
Und
State = Closed
Dann
Toröffner betätigen
Setze State = Opening

Sonst wenn
Target = Open
Und
DeinSensor = Open
Und
 State = Opening
Dann
Setze State = Open (verzögert um Wirklicher Fahrtzeit)

Sonst wenn
Target = Closed
Und
DeinSensor = Open
Und
State = Open
Dann
Toröffner betätigen
Setze State = Closing

Sonst wenn
Target = Closed
Und
DeinSensor = Closed
Und
State = Closing
Dann
State = Closed

Denke so sollte es klappen. Bei State nur prüfen. Bei den anderen bei Änderung. 
Ich habe bei mir noch keinen Sensor dran.

**Comment by thoduh** [comment]
Also, nach einigen Startschwierigkeiten :-) sieht mein Programm jetzt so aus und funktioniert sogar:

![bildschirmfoto 2018-03-04 um 11 50 11](https://user-images.githubusercontent.com/22728076/36944720-4674f968-1fa2-11e8-91dd-fa6042665772.png)

Da ich zwei Endlagenschalter (Garagentor Offen / Garagentor geschlossen) habe, muss ich das Programm noch etwas ändern.

=> Vielen Dank für die Unterstützung !!!

**Comment by mach1009** [comment]
Super! Das freut mich. 

@nicoh88 so sollte dein Programm auch aussehen.

**Comment by mach1009** [comment]
Es macht übrigens Sinn sich eine virtuelle Ferbedienung für das Realis des Garagentors anzulegen. Damit legt man einmal fest, wie lange es geschlossen bleiben soll und braucht nicht immer dran zu denken es zurückzusetzen. Außerdem spart man sich einen Sendevorgang.

![grafik](https://user-images.githubusercontent.com/25270782/36945522-ccabf466-1faf-11e8-896d-60a2d59f4341.png)

**Comment by thoduh** [comment]
Stimmt ja hatte ich ganz vergessen ;-)

Ein Problem gibt es aber noch:
Wenn das Garagentor in einer Kippstellung (zum Lüften) bleibt und sich nach 1 Stunde selbstständig schließt, wird HomeKit nicht aktualisiert und bleibt auf "Geöffnet" stehen.

Lässt sich eine Kippstellung ebenfalls in HomeKit darstellen oder geht nur "Wird geöffnet / Geöffnet" und "Wird geschlossen / Geschlossen"?

Durch meine zwei Endlagenschalter, kann ich bereits eine Systemvariable (Geöffnet / Geschlossen / Gekippt) füllen.
![bildschirmfoto 2018-03-04 um 17 36 27](https://user-images.githubusercontent.com/22728076/36947905-a90c9ace-1fd2-11e8-8662-2c2e5ffe12f9.png)

**Comment by mach1009** [comment]
Ich vermute mal werden nicht korrekt gesetzt. 
Target und State gehören in der Homeapp irgendwie zusammen. Wenn Target `Open` ist, darf State nicht `closing` sein. 
Das bekommst du ja raus, wenn du dir in dem Fall den Status der Variablen in der CCU anschaust. 
Denkbar wäre, dass du den Status `stopped` nutzt, wenn das Tor auf Lüftung steht. Das in einem Programm abzubilden wird bestimmt spaßig 😬.

**Comment by nicoh88** [comment]
@mach1009 Bedeutet das, dass die Logik des Plugin durcheinander gerät, wenn das Garagentor sich nicht öffnen konnte, weil ein Auto vor dem Tor steht und es somit direkt wieder zugegangen ist? :

Dies sollte schon korrekt funktionieren, wenn man des Plugin produktiv einsetzen möchte. 👍

**Comment by thoduh** [comment]
@nicoh88 
Sobald der normale Garagentoröffner benutzt wird, bekommt HomeKit davon leider nix mit...

**Comment by mach1009** [comment]
Je nachdem wieviele Sensoren man einsetzt bzw. wie schlau man sein Programm gestaltet, kann man die ganzen Status des Tores nachbilden. Evtl. werde ich den Blockadestatus noch mit implementieren. Kann leider noch nicht sagen, wie sich die Home App da verhält.

@thoduh Versuche doch mal in deinem Programm in dem du den Status auf, zu, gekippt rausbekommst bei dem Setzen deiner Variable den Target Wert mit zu setzen. 
Auf, gekippt = Open
Zu = Closed 
Evtl. Synchronisiert das dann die Bedienung mit der Fernbedienung.

**Comment by thoduh** [comment]
Hab ich heute versucht, funktioniert leider noch nicht richtig.
Wenn das Tor z.B. über den normalen Taster geschlossen wird, wird das auch in HomeKit zwar angezeigt, aber sobald es dann geschlossen ist, steht bei HomeKit „Wird geöffnet“...

Hab heute recht lange rumgespielt, teilweise wurde das Tor nach dem schließen sofort wieder geöffnet usw...

**Comment by mach1009** [comment]
Mhhh. Da kommen sich dann die Programme ins Gehege. Bei mir dauert es noch ein paar Wochen, bis ich alles so angeschlossen habe, dass ich selbst vor dem Problem stehe und das nachstellen kann. Von welchem Hersteller ist dein Antrieb?

**Comment by thoduh** [comment]
@mach1009 NovoPort III

**Comment by mach1009** [comment]
Mache hier erstmal zu.
