### ISSUE TITLE
Änderungen zu "Original"?

### ISSUE THREAD

**Issue by dkrizic** [mach1009/homebridge-http-garagedoor#2]
Hi,

hat Dein Fork Änderungen zum Original von codetwice?

Gruß,

Darko

**Comment by mach1009** [comment]
Ja, klar.

codetwice Original bildet ein Security System ab. Das habe ich selbst auch noch zu laufen um mir meine Alarmanlage in der Homematic abzubilden. 

Warum die Frage?

Grüße
